### ISSUE TITLE
issue when launching sommelier

### ISSUE THREAD

**Issue by Spagett1** [akvadrako/sommelier#4]
hi, when im launching sommelier i recieve an error about wl0

**Comment by Laar3** [comment]
accidentally submitted before i finished
the error i recieve is
`error: could not open /dev/wl0 (No such file or directory)`
this happens when running `GDK_BACKEND=x11 GDK_SCALE=2 sommelier -X --scale=2 gedit -s --gdk-debug=misc` and when launching sommelier in any other way, however `sommelier --help` works fine and prints out correctly

**Comment by Laar3** [comment]
this issue happens both on the river window manager aswell as sway

**Comment by Merlin04** [comment]
I was experiencing this error too, I fixed it by changing line 4016 of sommelier.c to `if(false && virtwl_device) {` to disable the if statement and making the same change on 4083, then in meson_options.txt updating lines 7 and 13 to point to the proper paths (`/usr/bin/Xwayland` and `/lib` for me).
